export const ACTIONS = {
  TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
  LOGIN_SUBMIT: 'LOGIN_SUBMIT',
  CONNECTION_STATUS_CHANGE: 'CONNECTION_STATUS_CHANGE',
  ON_ERROR: 'ON_ERROR',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  MESSAGE_SUBMIT: 'MESSAGE_SUBMIT',
};

export default { ACTIONS };
